# Generated by Django 5.0.7 on 2024-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
