# Generated by Django 5.0.7 on 2024-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_product_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usdprice',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
