# Generated by Django 5.0.7 on 2024-08-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_product_usdprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='usdprice',
            new_name='usd_price',
        ),
    ]
