# Generated by Django 5.0.7 on 2024-08-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
