# Generated by Django 5.0.7 on 2024-08-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product_file',
            new_name='profile_img',
        ),
    ]
